
char * FUN_00623330(void)

{
  return "std::exception";
}

